JIRA:MGMTAGENT-7403- Terraform scripts for Management Gateway Marketplace
oracle-quickstart/oci-management-agent pull request #5
Opened 2022-12-05 05:57 UTC by SaiPurnimaPatro

Management Gateway QuickStart Terraform scripts will create dynamic groups and policies in a specific compartment

2022-12-14 22:20 UTC, niravg75 approved these changes

2022-12-14 22:23 UTC, niravg75 requested changes
Can you make the changes in the workflow to create a separate zip for the gateway policy MP app?

2022-12-14 22:41 UTC, niravg75 commented
Also the branch name should be:  feature/<your user id>/v1.0.4

2022-12-19 05:39 UTC, closed without merging

2022-12-19 05:40 UTC, SaiPurnimaPatro commented
Will create a new pull request by addressing review comments in a new branch with name as required.